spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tactical_medicine_db
    username: postgres
    password: 090420

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
