spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tactical_medicine_db
    username: tactical_user
    password: strong_password_here

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

app:
  jwt:
    secret: "my-super-secret-key-12345678901234567890"
    expiration-ms: 86400000

    recommendation:
        weights:
          problem: 0.6
          difficulty: 0.2
          criticality: 0.2