package com.example.demo.scenario.enums;

public enum MarchActionTrigger {
    ALWAYS,
    ACTIVE_BLEEDING,
    AIRWAY_COMPROMISED,
    BREATHING_COMPROMISED,
    CONSCIOUSNESS_AFFECTED,
    PAIN_MANAGEMENT_REQUIRED,

    PAIN_ORAL_ROUTE,
    PAIN_TRANSMUCOSAL_ROUTE,
    PAIN_INTRANASAL_ROUTE,
    PAIN_IV_IO_ROUTE,

    ANTIBIOTICS_REQUIRED,
    ANTIBIOTICS_ORAL_ROUTE,
    ANTIBIOTICS_PARENTERAL_ROUTE,

    WOUND_CARE_REQUIRED,
    SPLINTING_REQUIRED
}